### PR TITLE
add .with_deleted in examples

### PR DESCRIPTION
**Pull request by kevintom**
- i find people often forget to update deleted rows, so update documentation to show that
- now people can opt out of updating deleted rows, but will be reminded to do it when they read the docs

### CODE REVIEW

**Comment by kevintom** [comment]
@shuber that might make sense.

I guess that depends on what the majority case is.

If you think that the majority use case is that, then we should do that.

thoughts?

**Comment by shuber** [comment]
@kevintom yea not sure if that's the majority case yet. I think for now we should update the validation error messages to match what you changed in the README then we can just merge and move forward. It wont be enforced but at least we'll be reminded in the error messages.

**Comment by siggymcfried** [comment]
FWIW, I tend to use `unscoped` since it can be called on any model (not just those that act as paranoid) and it handles other default scopes as well.

**Comment by shuber** [comment]
@siggymcfried that's a great suggestion - I think we should go that route instead 👍

**Pull request closed without merging**
